Repository paketo-buildpacks/apache-tomcat, pull requests merged in 2022-03, with the labels that each got.

#193 Revert "Switch to new Apache Downloads CDN"
  .github/pipeline-descriptor.yml
  .github/workflows/update-tomcat-10.yml
  .github/workflows/update-tomcat-8.yml
  .github/workflows/update-tomcat-9.yml
Labels: semver:patch, type:bug

#197 Bump to using Go 1.17 and fix module declarations to have major version suffix
  cmd/helper/main.go
  cmd/main/main.go
  go.mod
  go.sum
  helper/access_logging_support_test.go
  scripts/build.sh
  tomcat/base_test.go
  tomcat/build_test.go
  tomcat/detect_test.go
  tomcat/home_test.go
Labels: type:dependency-upgrade, semver:minor

#201 Implements RFC 0008 & 'BP_JAVA_APP_SERVER' for Apache Tomcat
  README.md
  buildpack.toml
  cmd/main/main.go
  tomcat/build.go
  tomcat/detect.go
  tomcat/detect_test.go
Labels: type:enhancement, semver:minor

#198 Configuring EnvironmentPropertySource to configure Tomcat config files
  README.md
  buildpack.toml
  tomcat/base.go
  tomcat/base_test.go
Labels: type:enhancement, semver:minor
